spring:
  application:
    name: base-redis
  redis:
    host: 192.168.99.122
    port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.122:5432/testdb?autoReconnect=true&useUnicode=true
    username: postgres
    password: 1234
    hikari:
      connection-test-query: select 1
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: dbcp1
mybatis:
  mapper-locations: classpath*:mapper/*.xml


